separator: ","
columns:
  - year
  - make
  - model
  - trim
  - body
  - transmission
  - vin
  - state
  - condition
  - odometer
  - color
  - interior
  - seller
  - mmr
  - sellingprice
  - saledate
